#!/bin/bash

echo "🔍 Checking GitHub Actions workflow status..."
echo "Repository: https://github.com/mister-weeden/et-al-Masapeta-Dhakal-Ravula-Zhang"
echo "Actions URL: https://github.com/mister-weeden/et-al-Masapeta-Dhakal-Ravula-Zhang/actions"
echo ""
echo "📋 Recent commits that should trigger the workflow:"
git log --oneline -5
echo ""
echo "🎯 To manually trigger the workflow:"
echo "1. Go to: https://github.com/mister-weeden/et-al-Masapeta-Dhakal-Ravula-Zhang/actions"
echo "2. Click on 'Build LaTeX PDF' workflow"
echo "3. Click 'Run workflow' button"
echo "4. Optionally enable debug mode"
echo "5. Click 'Run workflow' to start"
echo ""
echo "📁 Workflow file location: .github/workflows/build-pdf-on-pull-request.yaml"
echo "🎯 Triggers on:"
echo "  - Push to main branch (*.tex or *.bib files)"
echo "  - Pull requests (*.tex or *.bib files)"
echo "  - Manual dispatch (workflow_dispatch)"
